default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  username: postgres
  password: qwer1234
  host: localhost
  database: walletbitcoinapi_development

production:
  <<: *default
  sslmode: 'disable'
  username: postgres
  password: qwer1234
  host: localhost
  database: walletbitcoinapi_production