default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  username: postgres
  password: qwer1234
  host: localhost
  database: walletbitcoinapi_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: 'require'